### ISSUE TITLE
Incorrectly marking repeated letters

### ISSUE THREAD

**Issue by pawlos** [CrociDB/wordlos#1]
Thanks for this project :).
I think there's a small issue in the algorithm for providing green/yellow/grey information when the entered word has double letter and the correct one only has one.
 
I was guessing BALLS, BULLS when the correct word was BELOW and the game was reporting one correctly placed L and one incorrectly. 

![bug_Zrzut ekranu 2022-04-03 221857](https://user-images.githubusercontent.com/1296768/161582660-24dc0d79-8a51-4d10-b803-944bde695b04.png)

I think that it should not mark the second (misplaced) L as yellow and only as grey, right? Not sure if there are any official rules about wordle but found this on one of the sites explaining the game: "If you repeat a letter more than it appears, then the excess will be highlighted in grey."

Not expecting this to be fixed but if you are willing to accept PRs, I could refresh my DOS asm knowledge and try to fix this.

**Comment by CrociDB** [comment]
Hi Paweł, how are you doing? 

Sorry for the late response, for some reason I didn't get any email =/

Yeah, that was intentionally left aside in order to simplify the algorithm at first. I thought of fixing this at some point, but if you want to submit a fix, that will be happily accepted! I'm also just starting with assembly in general, so that would be a cool experience to see how you'd fix it! =D

Thank you!

**Comment by pawlos** [comment]
hi @CrociDB and thanks for your reply. Don't worry about it being late. 

Good to know that this was omitted intentionally so I won't be chasing a bug but try add new functionally. I was thinking a bit about this and it might add some complexity but nonetheless it might be a good challenge to brush off some assembly.

**Comment by pawlos** [comment]
@CrociDB Sorry for late update took me some time to sit to the code. If I understood the design it works on an index into the huge array of words. I think the best approach change would be to make a copy of the word and work on that instead. Any exact hit green - would remove that letter from this copy (replace with '\0' maybe) and that should correctly prepare for the yellow matches that checks if the letter is in the word but not on the right spot. I think that should work and fix the problem, but appears would change some of the functions to not operate on index - I'll try to find some simples solution possible to this.

**Comment by CrociDB** [comment]
Hi @pawlos. Yeah, there's a huge array of words, and `game_selected_world` keeps the index to the randomly selected word.

Oh, copying the word before doing the check is a great idea, and you can do it in the beginning of the  `update_word_state` function, so it always starts off with the entire word. But only that won't work right now, because it checks for the greens and yellows in the same letter interation. I think in that case, we should check all greens before, then start all over and check all the yellows.

In `update_word_state`, it iterates over the user input word, more specifically in `_letter_iteration`. Then it checks if the current letter matches for green, otherwise it start's a new loop on the target word to match for yellow. If we separate the loop, then that can be achieved we very few changes.

It's funny how simple loops become complex structures in assembly. 😆

**Comment by pawlos** [comment]
Thanks for the additional info.

"we should check all greens before, then start all over and check all the yellows." - yes that was the idea, but I've must have missed the fact that green & yellow are checked together. That's a problem but splitting the checks - as you described - should work. 

> It's funny how simple loops become complex structures in assembly. 😆

Everything seems complex in assembly ;) but also with enough time everything can be understood :)

**Comment by pawlos** [comment]
@CrociDB Sorry I haven't been providing the PR yet. Had to change the order of going through letters (was from back to front - now front to back) and I'm discovering some corner cases here and there ;)

I have some work related work this week - I'll get back to this on next one.

**Comment by pawlos** [comment]
Created PR for this fix. Tried to limit changes as much as possible but few essential were needed to have a consistent state between the words and the keyboard with letters below. 

Please let me know if something should be changed

**Comment by CrociDB** [comment]
Thanks for the PR! It looks really cool. I just found one thing, right after I approved, however. It looks like it's not marking unused letters in the main board anymore:

![Issue](https://i.imgur.com/82Fje55.png)

It's still working normally on the keyboard, though.

**Comment by pawlos** [comment]
I guess not enough testing ;) Let me have another look.

**Comment by pawlos** [comment]
ok, think I've just deleted too much. It looks like it's ok
![image](https://user-images.githubusercontent.com/1296768/166502941-bbd1a87e-22cc-4148-ba36-f4b2fe4ca968.png)
I'll do a bit more testing and create new PR.

**Comment by crocidb** [comment]
Thanks, @pawlos, I merged and generated a new release with your change! :)
